receivers:
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 60s
    timeout: 20s
    metrics:
      container.cpu.utilization:
        enabled: true
      container.cpu.usage.total:
        enabled: true
      container.memory.usage.total:
        enabled: true
      container.memory.usage.limit:
        enabled: true
      container.memory.percent:
        enabled: true
      container.network.io.usage.rx_bytes:
        enabled: true
      container.network.io.usage.tx_bytes:
        enabled: true
      container.blockio.io_service_bytes_recursive:
        enabled: true

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

  resource:
    attributes:
      - key: host.name
        value: eshop-docker-host
        action: upsert
      - key: service.namespace
        value: eshop
        action: upsert

exporters:
  otlp_http/newrelic:
    endpoint: https://otlp.nr-data.net
    headers:
      api-key: ${env:NEW_RELIC_LICENSE_KEY}

service:
  telemetry:
    logs:
      level: info
  pipelines:
    metrics:
      receivers: [docker_stats]
      processors: [resource, batch]
      exporters: [otlp_http/newrelic]
