<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>eShop.Catalog.Module</RootNamespace>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" PrivateAssets="all" />
    <PackageReference Include="Pgvector" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" />
    <PackageReference Include="Aspire.Azure.AI.OpenAI" />
    <PackageReference Include="CommunityToolkit.Aspire.OllamaSharp" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\eShop.SharedKernel\eShop.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Ordering\Ordering.Contracts\Ordering.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Shared\MigrateDbContextExtensions.cs" Link="MigrateDbContextExtensions.cs" />
    <Compile Include="..\..\..\Shared\ActivityExtensions.cs" Link="ActivityExtensions.cs" />
  </ItemGroup>

</Project>
