<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>eShop.ApiHost</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eShop.ServiceDefaults\eShop.ServiceDefaults.csproj" />
    <ProjectReference Include="..\eShop.SharedKernel\eShop.SharedKernel.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Catalog.Module\Catalog.Module.csproj" />
    <ProjectReference Include="..\Modules\Basket\Basket.Module\Basket.Module.csproj" />
    <ProjectReference Include="..\Modules\Identity\Identity.Module\Identity.Module.csproj" />
    <ProjectReference Include="..\Modules\Ordering\Ordering.Module\Ordering.Module.csproj" />
    <ProjectReference Include="..\Modules\Payment\Payment.Module\Payment.Module.csproj" />
    <ProjectReference Include="..\Modules\Webhooks\Webhooks.Module\Webhooks.Module.csproj" />
  </ItemGroup>

</Project>
