<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>eShop.Identity.Module</RootNamespace>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Duende.IdentityServer" />
    <PackageReference Include="Duende.IdentityServer.AspNetIdentity" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\eShop.SharedKernel\eShop.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\eShop.ServiceDefaults\eShop.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Shared\MigrateDbContextExtensions.cs" Link="MigrateDbContextExtensions.cs" />
    <Compile Include="..\..\..\Shared\ActivityExtensions.cs" Link="ActivityExtensions.cs" />
  </ItemGroup>

</Project>
